import type {Metadata} from "next";
import "./globals.css";
import React, {ReactNode} from "react";
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <ClerkProvider appearance={{
            variables :{
                colorPrimary : '#da2626'
            }
        }}>
            <html lang="en">
            <body className={""}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
